name = "qsort"
version = "0.1.0"
defaultTargets = ["qsort"]

[[lean_lib]]
name = "Qsort"

[[lean_exe]]
name = "qsort"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.18.0"

[[require]]
name = "mpl"
git = "https://github.com/rish987/mpl"
# path = "/home/rish/mpl"
rev = "qsort"
